input_dir: "C:/PHYS3810/slant_edge_japan_best_192"
input_glob: "**/patch*.png"
output_dir: "mtf_outputs"

pixel_pitch_um: 4.6   # set if you want lp/mm
gamma: null           # e.g., 2.2 to approx linearise JPEGs
save_plots: true
